version: '3.4'
services:

  flask_app:
    image: first-flaskapp3
    build:
      context: .
      dockerfile: ./Dockerfile
      
    ports:
      - 8011:8000

    networks:

        - test

networks:

  test:

    external: true
    
